In the following, we show how to use **Support Vector Machines** for classification. We will use the famous IRIS data.  

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

from sklearn.svm import SVC
from sklearn.metrics import classification_report, confusion_matrix

**We import the data from the UCI repository:** 

In [2]:
# Input file containing 
url = "https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data"

# Assign colum names to the dataset
colnames = ['sepal-length', 'sepal-width', 'petal-length', 'petal-width', 'Class']

# Read dataset to pandas dataframe
irisdata = pd.read_csv(url, names=colnames)

# Prepare the data
X = irisdata.drop('Class', axis=1)
y = irisdata['Class']

**Split the data into train and test sets**

In [3]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20)

**Scale the data**

In [4]:
scaler = StandardScaler()
# Fit only to the training data
scaler.fit(X_train)
StandardScaler(copy=True, with_mean=True, with_std=True)

StandardScaler()

In [5]:
# Now apply the transformations to the data:
#X_train = scaler.transform(X_train)
#X_test = scaler.transform(X_test)


**Create the SVM classifier with a specific kernel**

In [6]:
# Create SVM classifier

#svclassifier = SVC(kernel='linear')
#svclassifier = SVC(kernel='poly', degree=5)
svclassifier = SVC(kernel='rbf')
#svclassifier = SVC(kernel='sigmoid')


**Train the classifier**

In [7]:
# Train the classifier 
svclassifier.fit(X, y)

SVC()

**Making Predictions**

In [8]:
# predict the test sample
y_pred = svclassifier.predict(X_test)


**Display the confusion matrix and performance measures** 

In [9]:
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[ 8  0  0]
 [ 0 10  0]
 [ 0  1 11]]
                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00         8
Iris-versicolor       0.91      1.00      0.95        10
 Iris-virginica       1.00      0.92      0.96        12

       accuracy                           0.97        30
      macro avg       0.97      0.97      0.97        30
   weighted avg       0.97      0.97      0.97        30

